// src/app/employee.model.ts
// This interface defines the structure of an Employee object,
// matching the Employee DTO/POJO in your Spring Boot backend.
export interface Employee {
  id?: number; // Optional: ID is typically generated by the backend for new employees
  name: string;
  phone: string;
  email: string;
}